In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

# Data Management

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
# filtering the data to only useful columns 
# genre, keywords, title, overview, popularity, voteavg, votecount
movies = movies[['title', 'genres', 'overview', 'keywords', 'popularity', 'vote_average', 'vote_count']]
#since we will merge data on basis of "title" we can filter movie id from credits csv too
credits = credits[['title', 'cast', 'crew']]

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         4803 non-null   object
 1   genres        4803 non-null   object
 2   overview      4800 non-null   object
 3   keywords      4803 non-null   object
 4   popularity    4803 non-null   float64
 5   vote_average  4803 non-null   float64
 6   vote_count    4803 non-null   int64
dtypes: float64(2), int64(1), object(4)
memory usage: 187.7+ KB

In [7]:
movies = movies.merge(credits, on='title')

In [8]:
movies.isnull().sum()

title           0
genres          0
overview        3
keywords        0
popularity      0
vote_average    0
vote_count      0
cast            0
crew            0
dtype: int64

In [9]:
movies.dropna(inplace=True)
#now no null values are present

#extrcting useful information from genre, cast, crew, keywords

In [10]:
movies.genres.head()

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [11]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
from ast import literal_eval 
#literal_eval is used to covert given string to list for easy exctation
def extract(x):
    List=[]
    for i in literal_eval(x):
        List.append(i['name'])
    return List

In [13]:
movies['genres'] = movies['genres'].apply(extract)

In [14]:
movies['keywords'] = movies['keywords'].apply(extract)

In [15]:
movies.head()

,title,genres,overview,keywords,popularity,vote_average,vote_count,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",150.437577,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...",139.082615,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",107.376788,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...",112.312950,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...",43.926995,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

#From cast we will only take top 4 cast and from crew we will only pick the director

In [16]:
# We only need top 4 cast members name.

In [17]:
def extract_4(x):
    List=[]
    count = 0
    for i in literal_eval(x):
        List.append(i['name'])
        count+=1
        if count >= 4:
            break
    return List

In [18]:
movies['cast'] = movies['cast'].apply(extract_4)

In [19]:
movies['cast'][0]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang']

In [20]:
def extract_direc(x):
    List=[]
    for i in literal_eval(x):
        if i['job'] == "Director":
            List.append(i['name'])
            break
    return List

In [21]:
movies['crew'] = movies['crew'].apply(extract_direc)

In [22]:
movies.head()

,title,genres,overview,keywords,popularity,vote_average,vote_count,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",150.437577,7.2,11800,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...",139.082615,6.9,4500,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bondâ€™s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",107.376788,6.3,4466,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...",112.312950,7.6,9106,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...",43.926995,6.1,2124,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

# Converting information of each movie to tags

In [23]:
#converting overview string to list of characters
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [24]:
#creared a copy of dataset for further use
#new_m = movies.copy()

In [25]:
#removing unwanted spaces from all the attributes so that a single entry is not converted into separate tags 
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x]) 
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [26]:
movies.head()

,title,genres,overview,keywords,popularity,vote_average,vote_count,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...",150.437577,7.2,11800,"[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...",139.082615,6.9,4500,"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bondâ€™s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...",107.376788,6.3,4466,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...",112.312950,7.6,9106,"[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...",43.926995,6.1,2124,"[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [27]:
movies['title'][0]

'Avatar'

In [28]:
movies['tags'] = movies['title'].apply(lambda x:x.split()) + movies['cast'] + movies['crew'] + 2*movies['genres'] + movies['keywords'] + movies['overview']

In [29]:
movies['weighted_avg'] = (movies['vote_count'] * movies['vote_average'])
movies['weighted_avg']

0       84960.0
1       31050.0
2       28135.8
3       69205.6
4       12956.4
         ...
4804     1570.8
4805       29.5
4806       42.0
4807       39.9
4808      100.8
Name: weighted_avg, Length: 4806, dtype: float64

In [30]:
movies['weighted_avg'] = movies['weighted_avg'] - movies['weighted_avg'].mean()
movies['weighted_avg'] = movies['weighted_avg']/4803
movies['weighted_avg'].describe()

count    4.806000e+03
mean    -9.462076e-17
std      1.880279e+00
min     -9.722848e-01
25%     -9.047333e-01
50%     -6.762928e-01
75%      1.589962e-02
max      2.221972e+01
Name: weighted_avg, dtype: float64

In [31]:
movies['weighted_avg'] = movies['weighted_avg']/movies['weighted_avg'].max()
movies['weighted_avg'].describe()

count    4.806000e+03
mean    -4.435348e-18
std      8.462210e-02
min     -4.375774e-02
25%     -4.071758e-02
50%     -3.043660e-02
75%      7.155635e-04
max      1.000000e+00
Name: weighted_avg, dtype: float64

In [32]:
movies = movies[['title', 'tags']]

In [33]:
movies.head()

,title,tags
0,Avatar,"[Avatar, SamWorthington, ZoeSaldana, Sigourney..."
1,Pirates of the Caribbean: At World's End,"[Pirates, of, the, Caribbean:, At, World's, En..."
2,Spectre,"[Spectre, DanielCraig, ChristophWaltz, LÃ©aSeyd..."
3,The Dark Knight Rises,"[The, Dark, Knight, Rises, ChristianBale, Mich..."
4,John Carter,"[John, Carter, TaylorKitsch, LynnCollins, Sama..."

In [34]:
movies['tags'] = movies['tags'].apply(lambda x:" ".join(x))

In [35]:
movies['tags'] = movies['tags'].apply(lambda x:x.lower())

In [36]:
movies['tags'][0]
#tags of avatar

'avatar samworthington zoesaldana sigourneyweaver stephenlang jamescameron action adventure fantasy sciencefiction action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

Now from all the tags combined we will search for the most frequently occurings tags and on the basis of those frequently occurings tags we will decide how similar the given movies are.
But before that we will use nlp library "nltk" to merge all the similar occuring words for example: 'become', 'becomes', 'becoming' all are same words but can be considered different. Hence we will stem these data so that all become the same

In [37]:
#import nltk

In [38]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [39]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [40]:
# An example 
stem('love, loving')

'love, love'

In [41]:
movies['tags'] = movies['tags'].apply(stem)

In [42]:
movies.head()

,title,tags
0,Avatar,avatar samworthington zoesaldana sigourneyweav...
1,Pirates of the Caribbean: At World's End,pirat of the caribbean: at world' end johnnyde...
2,Spectre,spectr danielcraig christophwaltz lÃ©aseydoux r...
3,The Dark Knight Rises,the dark knight rise christianbal michaelcain ...
4,John Carter,john carter taylorkitsch lynncollin samanthamo...

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 6000, stop_words='english')

In [44]:
#CountVectorizer converts a collection of text documents to a matrix of token counts.

In [45]:
matrix = cv.fit_transform(movies['tags']).toarray()

In [46]:
matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
cv.get_feature_names()

c:\program files (x86)\python37-32\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '13th',
 '14',
 '15',
 '150',
 '16',
 '17',
 '17th',
 '18',
 '1890',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1967',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1995',
 '1997',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2000',
 '2001',
 '2003',
 '2009',
 '20th',
 '21',
 '21st',
 '23',
 '24',
 '25',
 '27',
 '28',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '51',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abbi',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abov',
 'abroad',
 'absolut',
 'absurd',
 'abus',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adambrodi',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adrift',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airborn',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanalda',
 'alanarkin',
 'alaska',
 'albert',
 'albertbrook',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alejandrogonzÃ¡leziÃ±Ã¡rritu',
 'alex',
 'alexapenavega',
 'alexisbledel',
 'alexkendrick',
 'alfi',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'algeria',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'alleg',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allisonjanney',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alvin',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientgreec',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'andrewniccol',
 'android',
 'andy',
 'andyfickman',
 'andygarcÃ­a',
 'andyserki',
 'andytenn',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annabel',
 'annafari',
 'annakendrick',
 'annapaquin',
 'annasophiarobb',
 'anne',
 'annebancroft',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antarct',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'apollo',
 'appar',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'aquarium',
 'arab',
 'arbitrarylaw',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arizona',
 'arm',
 'armageddon',
 'armi',
 'armiehamm',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'array',
 'arrest',
 'arriv',
 'arrives',
 'arrog',
 'arson',
 'art',
 'artgalleri',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'artists',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'ass',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atlant',
 'atlanta',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'aviat',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'backyard',
 'bad',
 'bag',
 'bahama',
 'bail',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bang',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbara',
 'barbarahershey',
 'barbarian',
 'barbershop',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barry',
 'barrylevinson',
 'barrypepp',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedonchildren',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'bathtub',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'behead',
 'belgium',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berniemac',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billion',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyburk',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'biograph',
 'biographi',
 'biolog',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bittersweet',
 'bizarr',
 'black',
 'blackandwhit',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blakel',
 'blame',
 'blart',
 'blast',
 'blaze',
 'blend',
 'bless',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blog',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blu',
 'blue',
 'blunt',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bohemian',
 'bold',
 'bollywood',
 'bolt',
 'bomb',
 'bomber',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'boot',
 'border',
 'bore',
 'boredom',
 'boring',
 'born',
 'borrow',
 'boss',
 'boston',
 'botch',
 'bottl',
 'bounc',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bourn',
 'bout',
 'bowl',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'braddourif',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brass',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakfast',
 'breakingthefourthwal',
 'breakup',
 'breast',
 'breath',
 'breckinmey',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briancox',
 'briandepalma',
 'brianlev',
 'brianrobbin',
 'brick',
 'bride',
 'bridesmaid',
 'bridg',
 'bridgetfonda',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronson',
 'bronx',
 'brood',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brotherhood',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucedern',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryancranston',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'budapest',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'buffalo',
 'bug',
 'build',
 'building',
 'built',
 'bull',
 'bullet',
 'bulli',
 'bum',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butch',
 'butcher',
 'butler',
 'butt',
 'butterfli',
 'button',
 'buy',
 'buzz',
 'cabin',
 'cabl',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'cal',
 'caleb',
 'california',
 'calm',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'cameroncrow',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannabi',
 'cannib',
 'canuxploit',
 'canyon',
 'capabl',
 'cape',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'cargo',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carlo',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherineo',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'cedrictheentertain',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'chair',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charless',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlott',
 'charlotterampl',
 'charm',
 'chart',
 'chase',
 'chasesandrac',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'chocol',
 'choic',
 'choice',
 'choir',
 'chon',
 'choos',
 'chosen',
 'chosenon',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasev',
 'christmasparti',
 ...]

In [48]:
matrix.shape

(4806, 6000)

In [49]:
from sklearn.metrics.pairwise import cosine_similarity
#returns dot product

In [50]:
similarity = cosine_similarity(matrix)

In [51]:
similarity

array([[1.        , 0.23310861, 0.18852561, ..., 0.04997225, 0.        ,
        0.        ],
       [0.23310861, 1.        , 0.17253244, ..., 0.03429972, 0.01889822,
        0.01889822],
       [0.18852561, 0.17253244, 1.        , ..., 0.01849317, 0.        ,
        0.        ],
       ...,
       [0.04997225, 0.03429972, 0.01849317, ..., 1.        , 0.03241019,
        0.04861528],
       [0.        , 0.01889822, 0.        , ..., 0.03241019, 1.        ,
        0.07142857],
       [0.        , 0.01889822, 0.        , ..., 0.04861528, 0.07142857,
        1.        ]])

In [52]:
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:21]
    
    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [53]:
def recommend2():
    #num_of_movies = input('Number of movies: ')
    a = [movie for movie in input("Enter movies: ").split(", ")]
    num_of_movies = len(a)
    #movie_index_list = [movies[movies['title'] == movie].index[0]]
    movie_index_list = [movies[movies['title'] == movie].index[0] for movie in a]
    x = np.linspace(0, 0, 6000)
    for i in movie_index_list:
        x = x + matrix[i]
    #cummulative vector of all movies
    List=[]
    for i in range(4806):
        t = np.dot(x, matrix[i])
        List.append(t)
    movie_list = sorted(list(enumerate(List)),reverse=True,key=lambda x:x[1])[num_of_movies:10+num_of_movies]
        
    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [63]:
recommend("Titanic")

Raise the Titanic
The Notebook
Code 46
Ghost Ship
Love Letters
Under the Same Moon
The Shipping News
Wicker Park
Alone With Her
Partition
Angel Eyes
The Switch
Poseidon
Veer-Zaara
Lovely, Still
Pandora's Box
The Rose
Moonlight Mile
My Summer of Love
Rent

In [ ]:
recommend2()